server:
  host: "0.0.0.0"
  port: 21002

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

umacs:
  tc_ip: "172.20.xx.xx"
  tc_port: "21003"
  data_server_ip: "172.20.xx.xx"
  api_req_source: "pcc"
  api_req_priority: "normal"
  api_req_execution_mode: "auto"
  api_req_subsystem: "payload"
